### ISSUE TITLE
Failure: nifcloud-debugcli computing upload-ssl-certificate ([Errno 2] No such file or directory)

### ISSUE THREAD

**Issue by yoshd** [nifcloud/nifcloud-sdk-python#13]
## Issue type

Bug report

## Summary

* `nifcloud-debugcli` でcomputingのupload-ssl-certificateで `--ca` オプションを指定すると、証明書バンドルのオプションとして扱われ(おそらく `--ca-bundle` と同様に扱われる)、CA証明書をアップロードできない

## Step to reproduce

```
$ nifcloud-debugcli computing upload-ssl-certificate --ca <Your CA string> --certificate <Your Certificate string> --key <Your Key string> --debug
※省略
2018-07-22 20:48:57,500 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=UploadSslCertificate) (verify_ssl=<Your CA string>) with params: ※省略
[Errno 2] No such file or directory
```

* `--debug` オプションを指定して確認すると、 `verify_ssl` に　`--ca` で指定した文字列が指定されていることがわかり、 `--ca-bundle` オプションを指定した場合と同様になる
    * [aws-cli](https://github.com/aws/aws-cli#other-configurable-variables)
* おそらく `--ca-bundle` と同様に指定された値をファイルパスとして探すため `[Errno 2] No such file or directory` となっている

## Expected behavior

* `--ca` オプションで指定したCA証明書がアップロードされる

```
$ nifcloud-debugcli computing upload-ssl-certificate --ca <Your CA string> --certificate <Your Certificate string> --key <Your Key string>
{
    "Fqdn": "hoge.example.com",
    "FqdnId": "0000",
    "RequestId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
}
```

**Comment by alice02** [comment]
`--ca` を `--certificate-authority` と指定できるように v0.2.2 で改修することにより、本事象は回避できるようになりました。
