### ISSUE TITLE
Failure: nifcloud-debugcli nas get-metric-statistics (invalid literal for int() with base 10)

### ISSUE THREAD

**Issue by ddeeff** [nifcloud/nifcloud-sdk-python#67]
# Issue type

- Bug report

# Summary

- nifcloud-debugcli でnasのget-metric-statisticsを実行するとエラーになる
- 恐らく想定している型(Integer)と返ってきている型(Double)が異なると思われる

# Step to reproduce

```
$ nifcloud-debugcli nas get-metric-statistics --start-time 2021-08-24T16:25:00Z --dimensions Name=NASInstanceIdentifier,Value=jpe12maeda03 --metric-name FreeStorageSpace

invalid literal for int() with base 10: '1038077673472.0'
```

# Expected behavior

- 指定したNASの残り容量が返ってくる

# Details

- get-metric-statistics に関しては以下の定義がマッチしてないように見える
  - https://github.com/nifcloud/nifcloud-sdk-python/blob/412b9d09ecf3f02d3dcd2b64000d8074350d2dd8/nifcloud/data/nas/N2016-02-24/service-2.json#L379
- `"shape": "Integer"` -> `"shape": "Double"` にしたら動作するようになった
  - 自分のケースでしか見ていないので、もしかしたら他のメトリックを指定するとIntergerが返ってくるのかもしれないが未確認 
```
$ nifcloud-debugcli nas get-metric-statistics --start-time 2021-08-24T16:25:00Z --dimensions Name=NASInstanceIdentifier,Value=jpe12maeda03 --metric-name FreeStorageSpace
{
    "Datapoints": [
        {
            "SampleCount": 1,
            "Sum": 1033608298496.0,
            "TargetName": "jpe12maeda03",
            "Timestamp": "2021-08-24T16:25:52+09:00"
        }
    ],
    "Label": "FreeStorageSpace"
}
```

**Comment by fuku2014** [comment]
Fixed by release v0.12.0 🎉
